FROM apache/airflow:2.2.2
RUN python -m pip install python-dotenv
RUN pip install boto3==1.20.3
RUN pip install mygeotab==0.8.6
RUN pip install pandas==1.0.3
RUN pip install psycopg2-binary
RUN pip install python-dotenv==0.19.2
RUN pip install SQLAlchemy==1.3.24

